# Generated by Django 5.0.3 on 2024-07-24 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('LongDistance', 'Long Distance'), ('LocalMoving', 'Local Moving'), ('MovingKits', 'Moving Kits'), ('StorageUnits', 'Storage Units'), ('BookDelivery', 'Book Delivery'), ('LoadingUnloading', 'Loading/Unloading')], max_length=100)),
                ('source_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('lorry', 'Lorry'), ('pickup', 'Pickup'), ('van', 'Van')], max_length=10)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.driver')),
            ],
        ),
    ]
